### ISSUE TITLE
SecureArray.SetProcessWorkingSetSizeEx unbalances stack

### ISSUE THREAD

**Issue by pukovec** [mheyman/Isopoh.Cryptography.Argon2#6] opened 2017-09-08 16:18 UTC
When I use Argon2 in Release on Win10 x64bit, the following exception is thrown:
(seems like a mismatch in function signature - wrong params or their types)

```
Additional information: A call to PInvoke function 
'Isopoh.Cryptography.SecureArray!Isopoh.Cryptography.SecureArray.SecureArray::SetProcessWorkingSetSizeEx' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.
```

**Comment by mheyman** [comment] 2017-09-10 23:09
Hmm, that doesn't happen on my Win10 64-bit.

The calling convention issue I think is a red herring because the default
is WinApi and that call is in kernel32.dll which is about as WinApi as you
can get.

I'm thinking it might be a 32-bit vs 64-bit issue which you can get on
64-bit systems. I tried to reproduce the problem and failed.

You forced me to realize that there was a latent bug for Win10 32-bit
systems. I added code to fix that but it probably won't make a difference
for you (but may). I cannot test that code (similarly, I cannot test the
MacOS code).

If you pull the 1.0.3 version of SecureArray from NuGet, you will get the
updated code that _could_ fix your problem. Until I can reproduce your
problem, I'm going to have a hard time validating any fix.

**Comment by paulhickman** [comment] 2017-09-23 14:53
How about making it injectable:

1. Declare an interface ISecureArray with the public methods of SecureArray
2. Add a constructor for the Argon2 class that takes an Func<int,ISecureArray> factory function as an argument.
2, Have the default constructor pass BestSecuryArray as the factory function. 

That way, uses can replace SecureArray with their own implementation if there are issues on a particular platform, and you can inject a mock array in test functions  if that helps.

**Comment by mheyman** [comment] 2017-09-24 13:33
That was my first idea to architect the system when I added Linux (an the
untested OSX) support. Unfortunately, ISecureArray would be a generic
interface and, while C# lets you do something like:

        public int Foo<T>(T arg)
        {
            return 0;
        }
        public void Bar()
        {
            Func<int, int> fooFunc = Foo<int>;
            fooFunc(7);
        }

It doesn't let you do:
        public void Bar()
        {
            Func<T, int> fooFunc = Foo;
            fooFunc<int>(7);
        }

The Argon2/Blake2b code only uses ISecureArray<byte> and
ISecureArray<ulong>, so for that code passing in two Func<>s wouldn't be
too bad, I decided the cleaner implementation was to split out the
platform-specific operations inside SecureArray. But, you have given me the
idea of injecting a type that has the three functions SecureArray uses
(zero, lock, and unlock memory). I'll work on that when I get a chance.

**Comment by mheyman** [comment] 2017-10-29 16:05
I have added a SecureArrayCall class that holds the methods used by SecureArray to actually secure the array.

There is a SecureArray.DefaultCall property that will get populated with the basic calls for Windows/Linux/OSx. In a unit test, I create a SecureArrayCall that wraps calls in SecureArray.DefaultCall to track locks (and I found a situation where I didn't free a lock - fixed in 1.0.5).

The Argon2 calls (should) now all have an optional parameter so they can use a non-default SecureArrayCall to get non-default behavior.

**Comment by thomasd3** [comment] 2017-12-03 21:21
Same message here:

> Managed Debugging Assistant 'PInvokeStackImbalance' : 'A call to PInvoke function 'Isopoh.Cryptography.SecureArray!Isopoh.Cryptography.SecureArray.SecureArray::SetProcessWorkingSetSizeEx64' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.'

That's with .NET 4.7 "AnyCpu" on Windows Server 2016

**Comment by mheyman** [comment] 2017-12-03 23:20
I think I can get access to a WinServer 2016 VM. I'll see if I can reproduce this as soon as I can.

**Comment by mheyman** [comment] 2018-01-13 15:45
It was a bug! I had flipped 32/64-bit P/Invokes and I never hit it until I added a .Net Framework test (which I had removed a long time ago as painful to maintain). The testing here is woefully incomplete because of the multitude of platforms and configurations it _theoretically_ runs on...

1.0.6 version at https://www.nuget.org/packages/Isopoh.Cryptography.Argon2/ has the fix.

**Closed by mheyman** 2018-01-13 15:45 UTC
